# Generated by Django 4.0.5 on 2022-11-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nganhnghe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangkinhdoanh', models.CharField(max_length=200)),
                ('mota', models.TextField(blank=True, null=True)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngayupdate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chitiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangkinhdoanh', models.CharField(max_length=200)),
                ('mota', models.TextField(blank=True, null=True)),
                ('hinhanh', models.ImageField(upload_to='hinhanh/%Y/%m')),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngayupdate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('nganhnghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kltp.nganhnghe')),
            ],
        ),
    ]
